### ISSUE TITLE
small multiples viewer settings not saving properly in a session

### ISSUE THREAD

**Issue by daskelly** [gluesolutions/glue-single-cell#44]
We saved a session that had both a 2D scatter plot and a small multiples viewer open. Both were colored according to a subset. Upon reopening the session, the 2D scatter plot settings were saved, but the small multiples viewer settings reverted to default and the coloring was lost. Is there a way to include these in the saved session?

**Comment by jfoster17** [comment]
I'll look into it -- should be a quick fix!

**Comment by jfoster17** [comment]
The Small Multiples Viewer is actually a standalone plug-in because it has broader use cases than just the single-cell case. It just gets installed automatically along with glue-single-cell. 

I have fixed this now in version 1.0.1 of glue-small-multiples

To update the small multiples viewer you should be able to just do:

pip install git+https://github.com/gluesolutions/glue-small-multiples.git
